enabled_categories:
  type: list
  list_type: category
  default: ""
  description: "Choose categories where the Shared Draft button should appear instead of New Topic."

button_text:
  type: string
  default: "New Shared Draft"
  description: "Text to display on the shared draft button."
